### ISSUE TITLE
Cannot find template

### ISSUE THREAD

**Issue by RockatanskyV8** [javabydeveloper/spring-boot#4]
I'm trying to run the example for send email with a template but thymeleaf cannot find it I allways get this error:

`
...
 Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/templates/forgot-password.html]
  at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:159) ~[spring-web-5.3.2.jar:5.3.2]
  at org.thymeleaf.spring5.templateresource.SpringResourceTemplateResource.reader(SpringResourceTemplateResource.java:103) ~[thymeleaf-spring5-3.0.11.RELEASE.jar:3.0.11.RELEASE]
  at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:223) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
  ... 102 common frames omitted
`

**Comment by Aditya-Mankar** [comment]
Hi, I was also getting the same error but I solved it by replacing "/templates/" with "classpath:/templates/" for the prefix in the config.
![image](https://user-images.githubusercontent.com/51234261/133551434-89cb8cdf-b98e-49ae-bf86-18873d31bce7.png)
